package com.albayan.quran

import android.content.Context
import android.os.Build
import android.util.Log
import java.util.Calendar
import java.util.Date
import java.time.LocalDate
import java.time.ZoneId
import java.time.chrono.HijrahDate
import java.time.temporal.ChronoField

/**
 * Native Hijri Date Calculator & Synchronizer
 * Tier 1: TypeScript JSON Cache (Absolute Source of Truth - Umm Al-Qura)
 * Tier 2: Native Android 8+ (Infinite Sustainability - Umm Al-Qura via java.time)
 * Tier 3: Native Android <8 (Legacy Tabular Fallback)
 */
object HijriUtil {

    private const val TAG = "HijriUtil"

    private val HIJRI_MONTHS = arrayOf(
        "محرم", "صفر", "ربيع الأول", "ربيع الثاني",
        "جمادى الأولى", "جمادى الآخرة", "رجب", "شعبان",
        "رمضان", "شوال", "ذو القعدة", "ذو الحجة"
    )

    data class HijriDate(val day: Int, val month: Int, val year: Int, val monthName: String)
    data class PrecalculatedHijri(val day: String, val month: String, val year: String, val remaining: String)

    /**
     * TIER 1: Read precalculated JSON map generated by TypeScript (Source of Truth)
     */
    fun getPrecalculatedHijriDate(context: Context, isoDate: String): PrecalculatedHijri? {
        try {
            val prefs = context.getSharedPreferences("AlBayanPersistence", Context.MODE_PRIVATE)
            val jsonStr = prefs.getString("hijriDatesJson", "{}")
            if (!jsonStr.isNullOrEmpty() && jsonStr != "{}") {
                val json = org.json.JSONObject(jsonStr)
                if (json.has(isoDate)) {
                    val obj = json.getJSONObject(isoDate)
                    return PrecalculatedHijri(
                        obj.getString("day"),
                        obj.getString("month"),
                        obj.getString("year"),
                        obj.getString("remaining")
                    )
                }
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error parsing hijriDatesJson", e)
        }
        return null
    }

    /**
     * TIER 2 & 3: Calculate Hijri Date natively.
     * Tier 2 uses java.time.chrono.HijrahDate (Umm al-Qura) for Android 8+.
     * Tier 3 uses Kuwaiti algorithm for legacy devices.
     */
    fun getHijriDate(date: Date, adjustment: Int = 0): HijriDate {
        // TIER 2: Native Umm Al-Qura (API 26+)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            try {
                // We apply adjustment to Gregorian date first, exactly like TypeScript's Intl.DateTimeFormat
                val localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate()
                val adjustedLocalDate = localDate.plusDays(adjustment.toLong())
                
                val hijrahDate = HijrahDate.from(adjustedLocalDate)
                val day = hijrahDate.get(ChronoField.DAY_OF_MONTH)
                val month = hijrahDate.get(ChronoField.MONTH_OF_YEAR)
                val year = hijrahDate.get(ChronoField.YEAR)
                
                val monthName = if (month in 1..12) HIJRI_MONTHS[month - 1] else ""
                
                Log.d(TAG, "Using Native Umm Al-Qura Engine (API 26+): $day $monthName $year (adj: $adjustment)")
                return HijriDate(day, month, year, monthName)
            } catch (e: Exception) {
                Log.e(TAG, "Failed to calculate native HijrahDate, falling back to tabular", e)
            }
        }

        // TIER 3: Legacy Tabular Fallback (Kuwaiti Algorithm)
        Log.d(TAG, "Using Legacy Tabular Engine (API < 26)")
        val cal = Calendar.getInstance()
        cal.time = date
        
        // Tabular base usually needs -1 to closely match Umm al-Qura, plus the user's manual offset
        val effectiveAdjustment = adjustment - 1
        if (effectiveAdjustment != 0) {
            cal.add(Calendar.DATE, effectiveAdjustment)
        }

        var day = cal.get(Calendar.DAY_OF_MONTH)
        var month = cal.get(Calendar.MONTH) // 0-based
        var year = cal.get(Calendar.YEAR)

        var m = month + 1
        var y = year
        if (m < 3) {
            y -= 1
            m += 12
        }

        var a = Math.floor(y / 100.0).toInt()
        var b = 2 - a + Math.floor(a / 4.0).toInt()
        
        if (y < 1583) b = 0
        if (y == 1582) {
            if (m > 10) b = -10
            if (m == 10) {
                b = 0
                if (day > 4) b = -10
            }
        }

        val jd = Math.floor(365.25 * (y + 4716)).toInt() + Math.floor(30.6001 * (m + 1)).toInt() + day + b - 1524

        val iyear = 10631.0 / 30.0
        val epochastro = 1948084
        val shift1 = 8.01 / 60.0

        var z = jd - epochastro
        val cyc = Math.floor(z / 10631.0).toInt()
        z -= 10631 * cyc
        val j = Math.floor((z - shift1) / iyear).toInt()
        val iy = 30 * cyc + j
        z -= Math.floor(j * iyear + shift1).toInt()
        var im = Math.floor((z + 28.5001) / 29.5).toInt()
        if (im == 13) im = 12
        val id = z - Math.floor(29.5 * im - 29.0).toInt()

        val hYear = iy
        val hMonth = im 
        val hDay = id

        val monthName = if (hMonth in 1..12) HIJRI_MONTHS[hMonth - 1] else ""

        return HijriDate(hDay, hMonth, hYear, monthName)
    }
}
